version: '3.8'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: typefaceadmin
      MYSQL_DATABASE: master
      MYSQL_USER: admin
      MYSQL_PASSWORD: typefaceadmin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: